services:
  - type: web
    name: portal-inmobiliario
    env: dotnet
    plan: free
    buildCommand: |
      dotnet restore
      # si tu .csproj NO está en la raíz, pon la ruta explícita:
      dotnet publish Portal-Inmobiliario/Portal-Inmobiliario.csproj -c Release -o out
    startCommand: dotnet out/Portal-Inmobiliario.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ConnectionStrings__DefaultConnection
        value: "Data Source=/tmp/portal.db"
      - key: Redis__ConnectionString
        value: "" # sin Redis -> usa caché en memoria
      - key: DOTNET_CLI_TELEMETRY_OPTOUT
        value: "1"
      - key: DOTNET_NOLOGO
        value: "1"
