services:
  - type: web
    name: portal-inmobiliario
    env: nixpacks
    plan: free
    autoDeploy: true

    buildCommand: dotnet publish ./Portal-Inmobiliario.csproj -c Release -o out
    startCommand: dotnet out/Portal-Inmobiliario.dll
    healthCheckPath: /

    disk:
      - name: data
        mountPath: /var/data
        sizeGB: 1

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/var/data/portal.db
      - key: DOTNET_CLI_TELEMETRY_OPTOUT
        value: "1"
      - key: DOTNET_NOLOGO
        value: "1"
