services:
  - type: web
    name: portal-inmobiliario
    plan: free
    autoDeploy: true

    buildCommand: dotnet publish ./Portal-Inmobiliario.csproj -c Release -o out
    startCommand: dotnet out/Portal-Inmobiliario.dll
    healthCheckPath: /

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      # Ojo: sin disco será NO persistente:
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=portal.db
